#!/bin/bash

# Copyright (c) 2019, Massachusetts Institute of Technology.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

sudo rm -rf /usr/bin/conda /usr/share/miniconda ~/.conda ~/.condarc

wget -nv https://drake-packages.csail.mit.edu/drake/continuous/drake-latest-bionic.tar.gz
tar -xf drake-latest-bionic.tar.gz
sudo mv drake /opt

export DEBIAN_FRONTEND=noninteractive
echo 'APT::Acquire::Retries "4";' | sudo tee /etc/apt/apt.conf.d/70-acquire-retries

sudo -E apt-get update -qq
sudo -E apt-get autoremove -o Dpkg::Use-Pty=0 -qq
sudo -E apt-get install -o Dpkg::Use-Pty=0 -qy --no-install-recommends xvfb

echo 'APT::Get::Assume-Yes "1";' | sudo tee /etc/apt/apt.conf.d/80-get-assume-yes
sudo -E /opt/drake/share/drake/setup/install_prereqs
sudo rm -f /etc/apt/apt.conf.d/80-get-assume-yes

sudo -E ./setup/ubuntu/install_prereqs.sh

sudo -E apt-get autoclean -qq
